### ISSUE TITLE
The API_KEY is public

### ISSUE THREAD

**Issue by MarounMaroun** [SOBotics/MiniTools#1]
Is it on purpose? 🤔

**Comment by Bhargav-Rao** [comment]
Yeah, API_KEY can be shared publicly. It is a per-IP  API Key. 

Thanks for your concern though, what if it wasn't. ;)

**Comment by Bhargav-Rao** [comment]
Just for the record, this is the description that is provided when requesting an API key: 

> This is not considered a secret, and may be safely embed in client side code or distributed binaries.

**Comment by MarounMaroun** [comment]
@Bhargav-Rao Great, thanks.
